	;(function($){
	var scrollbarNumber=0;
	var xScrollDistance=0;
	var yScrollDistance=0;
	var scrollIntervalTime=10;
	var scrollbarDistance=0;
	var isTouch=&#39;ontouchstart&#39;in window;
	var supportsOrientationChange=&#39;onorientationchange&#39;in window;
	var isWebkit=false;
	var has3DTransform=false;
	var isIe7=false;
	var isIe8=false;
	var isIe9=false;
	var isIe=false;
	var isGecko=false;
	var grabOutCursor=&#39;pointer&#39;;
	var grabInCursor=&#39;pointer&#39;;
	var onChangeEventLastFired=new Array();
	var autoSlideTimeouts=new Array();
	var iosSliders=new Array();
	var iosSliderSettings=new Array();
	var isEventCleared=new Array();
	var slideTimeouts=new Array();
	var activeChildOffsets=new Array();
	var activeChildInfOffsets=new Array();
	var infiniteSliderOffset=new Array();
	var sliderMin=new Array();
	var sliderMax=new Array();
	var sliderAbsMax=new Array();
	var touchLocks=new Array();
	var helpers={showScrollbar:function(settings,scrollbarClass)
				 {
					 if(settings.scrollbarHide){$(&#39;.&#39;+ scrollbarClass).css({opacity:settings.scrollbarOpacity,filter:&#39;alpha(opacity:&#39;+(settings.scrollbarOpacity*100)+&#39;)&#39;});}}
				 ,hideScrollbar:
				 function(settings,scrollTimeouts,j,distanceOffsetArray,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber){if(settings.scrollbar&amp;&amp;settings.scrollbarHide){
					 for(var i=j;i&lt;j+25;i++){scrollTimeouts[scrollTimeouts.length]=helpers.hideScrollbarIntervalTimer(scrollIntervalTime*i,distanceOffsetArray[j],((j+ 24)- i)/ 24, scrollbarClass, scrollbarWidth, stageWidth, scrollMargin, scrollBorder, sliderNumber, settings);
}}},hideScrollbarInterval:
				 function(newOffset,opacity,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber,settings){scrollbarDistance=(newOffset*-1)/ (sliderMax[sliderNumber]) * (stageWidth - scrollMargin - scrollBorder - scrollbarWidth);
helpers.setSliderOffset(&#39;.&#39;+ scrollbarClass,scrollbarDistance);$(&#39;.&#39;+ scrollbarClass).css({opacity:settings.scrollbarOpacity*opacity,filter:&#39;alpha(opacity:&#39;+(settings.scrollbarOpacity*opacity*100)+&#39;)&#39;});},slowScrollHorizontalInterval:function(node,slideNodes,newOffset,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,activeChildOffset,originalOffsets,childrenOffsets,infiniteSliderWidth,numberOfSlides,slideNodeOuterWidths,sliderNumber,centeredSlideOffset,endOffset,settings){if(settings.infiniteSlider){if(newOffset&lt;=(sliderMax[sliderNumber]*-1)){var scrollerWidth=$(node).width();if(newOffset&lt;=(sliderAbsMax[sliderNumber]*-1)){var sum=originalOffsets[0]*-1;$(slideNodes).each(function(i){helpers.setSliderOffset($(slideNodes)[i],sum+ centeredSlideOffset);if(i&lt;childrenOffsets.length){childrenOffsets[i]=sum*-1;}
sum=sum+ slideNodeOuterWidths[i];});newOffset=newOffset+ childrenOffsets[0]*-1;sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]=0;}else{var lowSlideNumber=0;var lowSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&lt;lowSlideOffset){lowSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);lowSlideNumber=i;}});var tempOffset=sliderMin[sliderNumber]+ scrollerWidth;helpers.setSliderOffset($(slideNodes)[lowSlideNumber],tempOffset);sliderMin[sliderNumber]=childrenOffsets[1]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;childrenOffsets.splice(0,1);childrenOffsets.splice(childrenOffsets.length,0,tempOffset*-1+ centeredSlideOffset);infiniteSliderOffset[sliderNumber]++;}}
if((newOffset&gt;=(sliderMin[sliderNumber]*-1))||(newOffset&gt;=0)){var scrollerWidth=$(node).width();if(newOffset&gt;=0){var sum=originalOffsets[0]*-1;$(slideNodes).each(function(i){helpers.setSliderOffset($(slideNodes)[i],sum+ centeredSlideOffset);if(i&lt;childrenOffsets.length){childrenOffsets[i]=sum*-1;}
sum=sum+ slideNodeOuterWidths[i];});newOffset=newOffset- childrenOffsets[0]*-1;sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]=numberOfSlides;while(((childrenOffsets[0]*-1- scrollerWidth+ centeredSlideOffset)&gt;0)){var highSlideNumber=0;var highSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&gt;highSlideOffset){highSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);highSlideNumber=i;}});var tempOffset=sliderMin[sliderNumber]- slideNodeOuterWidths[highSlideNumber];helpers.setSliderOffset($(slideNodes)[highSlideNumber],tempOffset);childrenOffsets.splice(0,0,tempOffset*-1+ centeredSlideOffset);childrenOffsets.splice(childrenOffsets.length-1,1);sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]--;activeChildOffsets[sliderNumber]++;}}
if(newOffset&lt;0){var highSlideNumber=0;var highSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&gt;highSlideOffset){highSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);highSlideNumber=i;}});var tempOffset=sliderMin[sliderNumber]- slideNodeOuterWidths[highSlideNumber];helpers.setSliderOffset($(slideNodes)[highSlideNumber],tempOffset);childrenOffsets.splice(0,0,tempOffset*-1+ centeredSlideOffset);childrenOffsets.splice(childrenOffsets.length-1,1);sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]--;}}}
var slideChanged=false;var newChildOffset=helpers.calcActiveOffset(settings,newOffset,childrenOffsets,stageWidth,infiniteSliderOffset[sliderNumber],numberOfSlides,activeChildOffset,sliderNumber);var tempOffset=(newChildOffset+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if(settings.infiniteSlider){if(tempOffset!=activeChildInfOffsets[sliderNumber])slideChanged=true;}else{if(newChildOffset!=activeChildOffsets[sliderNumber])slideChanged=true;}
if(slideChanged){var args=new helpers.args(&#39;change&#39;,settings,node,$(node).children(&#39;:eq(&#39;+ tempOffset+&#39;)&#39;),tempOffset,endOffset);$(node).parent().data(&#39;args&#39;,args);if(settings.onSlideChange!=&#39;&#39;){settings.onSlideChange(args);}}
activeChildOffsets[sliderNumber]=newChildOffset;activeChildInfOffsets[sliderNumber]=tempOffset;newOffset=Math.floor(newOffset);helpers.setSliderOffset(node,newOffset);if(settings.scrollbar){scrollbarDistance=Math.floor((newOffset*-1- sliderMin[sliderNumber]+ centeredSlideOffset)/ (sliderMax[sliderNumber] - sliderMin[sliderNumber] + centeredSlideOffset) * (scrollbarStageWidth - scrollMargin - scrollbarWidth));
var width=scrollbarWidth- scrollBorder;if(newOffset&gt;=(sliderMin[sliderNumber]*-1+ centeredSlideOffset)){width=scrollbarWidth- scrollBorder-(scrollbarDistance*-1);helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),0);$(&#39;.&#39;+ scrollbarClass).css({width:width+&#39;px&#39;});}else if(newOffset&lt;=((sliderMax[sliderNumber]*-1)+ 1)){width=scrollbarStageWidth- scrollMargin- scrollBorder- scrollbarDistance;helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),scrollbarDistance);$(&#39;.&#39;+ scrollbarClass).css({width:width+&#39;px&#39;});}else{helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),scrollbarDistance);$(&#39;.&#39;+ scrollbarClass).css({width:width+&#39;px&#39;});}}},slowScrollHorizontal:function(node,slideNodes,scrollTimeouts,scrollbarClass,xScrollDistance,yScrollDistance,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,currentEventNode,snapOverride,centeredSlideOffset,settings){var nodeOffset=helpers.getSliderOffset(node,&#39;x&#39;);var distanceOffsetArray=new Array();var xScrollDistanceArray=new Array();var snapDirection=0;var maxSlideVelocity=25/1024*stageWidth;var changeSlideFired=false;frictionCoefficient=settings.frictionCoefficient;elasticFrictionCoefficient=settings.elasticFrictionCoefficient;snapFrictionCoefficient=settings.snapFrictionCoefficient;if((xScrollDistance&gt;settings.snapVelocityThreshold)&amp;&amp;settings.snapToChildren&amp;&amp;!snapOverride){snapDirection=1;}else if((xScrollDistance&lt;(settings.snapVelocityThreshold*-1))&amp;&amp;settings.snapToChildren&amp;&amp;!snapOverride){snapDirection=-1;}
if(xScrollDistance&lt;(maxSlideVelocity*-1)){xScrollDistance=maxSlideVelocity*-1;}else if(xScrollDistance&gt;maxSlideVelocity){xScrollDistance=maxSlideVelocity;}
if(!($(node)[0]===$(currentEventNode)[0])){snapDirection=snapDirection*-1;xScrollDistance=xScrollDistance*-2;}
var tempInfiniteSliderOffset=infiniteSliderOffset[sliderNumber];if(settings.infiniteSlider){var tempSliderMin=sliderMin[sliderNumber];var tempSliderMax=sliderMax[sliderNumber];}
var tempChildrenOffsets=new Array();var tempSlideNodeOffsets=new Array();for(var i=0;i&lt;childrenOffsets.length;i++){tempChildrenOffsets[i]=childrenOffsets[i];if(i&lt;slideNodes.length){tempSlideNodeOffsets[i]=helpers.getSliderOffset($(slideNodes[i]),&#39;x&#39;);}}
while((xScrollDistance&gt;1)||(xScrollDistance&lt;-1)){xScrollDistance=xScrollDistance*frictionCoefficient;nodeOffset=nodeOffset+ xScrollDistance;if(((nodeOffset&gt;(sliderMin[sliderNumber]*-1))||(nodeOffset&lt;(sliderMax[sliderNumber]*-1)))&amp;&amp;!settings.infiniteSlider){xScrollDistance=xScrollDistance*elasticFrictionCoefficient;nodeOffset=nodeOffset+ xScrollDistance;}
if(settings.infiniteSlider){if(nodeOffset&lt;=(tempSliderMax*-1)){var scrollerWidth=$(node).width();var lowSlideNumber=0;var lowSlideOffset=tempSlideNodeOffsets[0];for(var i=0;i&lt;tempSlideNodeOffsets.length;i++){if(tempSlideNodeOffsets[i]&lt;lowSlideOffset){lowSlideOffset=tempSlideNodeOffsets[i];lowSlideNumber=i;}}
var newOffset=tempSliderMin+ scrollerWidth;tempSlideNodeOffsets[lowSlideNumber]=newOffset;tempSliderMin=tempChildrenOffsets[1]*-1+ centeredSlideOffset;tempSliderMax=tempSliderMin+ scrollerWidth- stageWidth;tempChildrenOffsets.splice(0,1);tempChildrenOffsets.splice(tempChildrenOffsets.length,0,newOffset*-1+ centeredSlideOffset);tempInfiniteSliderOffset++;}
if(nodeOffset&gt;=(tempSliderMin*-1)){var scrollerWidth=$(node).width();var highSlideNumber=0;var highSlideOffset=tempSlideNodeOffsets[0];for(var i=0;i&lt;tempSlideNodeOffsets.length;i++){if(tempSlideNodeOffsets[i]&gt;highSlideOffset){highSlideOffset=tempSlideNodeOffsets[i];highSlideNumber=i;}}
var newOffset=tempSliderMin- slideNodeOuterWidths[highSlideNumber];tempSlideNodeOffsets[highSlideNumber]=newOffset;tempChildrenOffsets.splice(0,0,newOffset*-1+ centeredSlideOffset);tempChildrenOffsets.splice(tempChildrenOffsets.length-1,1);tempSliderMin=tempChildrenOffsets[0]*-1+ centeredSlideOffset;tempSliderMax=tempSliderMin+ scrollerWidth- stageWidth;tempInfiniteSliderOffset--;}}
distanceOffsetArray[distanceOffsetArray.length]=nodeOffset;xScrollDistanceArray[xScrollDistanceArray.length]=xScrollDistance;}
var slideChanged=false;var newChildOffset=helpers.calcActiveOffset(settings,nodeOffset,tempChildrenOffsets,stageWidth,tempInfiniteSliderOffset,numberOfSlides,activeChildOffsets[sliderNumber],sliderNumber);var tempOffset=(newChildOffset+ tempInfiniteSliderOffset+ numberOfSlides)%numberOfSlides;if(settings.snapToChildren){if(settings.infiniteSlider){if(tempOffset!=activeChildInfOffsets[sliderNumber]){slideChanged=true;}}else{if(newChildOffset!=activeChildOffsets[sliderNumber]){slideChanged=true;}}
if((snapDirection&lt;0)&amp;&amp;!slideChanged){newChildOffset++;if((newChildOffset&gt;=childrenOffsets.length)&amp;&amp;!settings.infiniteSlider)newChildOffset=childrenOffsets.length- 1;}else if((snapDirection&gt;0)&amp;&amp;!slideChanged){newChildOffset--;if((newChildOffset&lt;0)&amp;&amp;!settings.infiniteSlider)newChildOffset=0;}}
if(settings.snapToChildren||(((nodeOffset&gt;(sliderMin[sliderNumber]*-1))||(nodeOffset&lt;(sliderMax[sliderNumber]*-1)))&amp;&amp;!settings.infiniteSlider)){if(((nodeOffset&gt;(sliderMin[sliderNumber]*-1))||(nodeOffset&lt;(sliderMax[sliderNumber]*-1)))&amp;&amp;!settings.infiniteSlider){distanceOffsetArray.splice(0,distanceOffsetArray.length);}else{distanceOffsetArray.splice(distanceOffsetArray.length*0.10,distanceOffsetArray.length);nodeOffset=(distanceOffsetArray.length&gt;0)?distanceOffsetArray[distanceOffsetArray.length-1]:nodeOffset;}
while((nodeOffset&lt;(tempChildrenOffsets[newChildOffset]- 0.5))||(nodeOffset&gt;(tempChildrenOffsets[newChildOffset]+ 0.5))){nodeOffset=((nodeOffset-(tempChildrenOffsets[newChildOffset]))*snapFrictionCoefficient)+(tempChildrenOffsets[newChildOffset]);distanceOffsetArray[distanceOffsetArray.length]=nodeOffset;}
distanceOffsetArray[distanceOffsetArray.length]=tempChildrenOffsets[newChildOffset];}
var jStart=1;if((distanceOffsetArray.length%2)!=0){jStart=0;}
var lastTimeoutRegistered=0;var count=0;for(var j=0;j&lt;scrollTimeouts.length;j++){clearTimeout(scrollTimeouts[j]);}
var endOffset=(newChildOffset+ tempInfiniteSliderOffset+ numberOfSlides)%numberOfSlides;var lastCheckOffset=0;for(var j=jStart;j&lt;distanceOffsetArray.length;j=j+ 2){if((j==jStart)||(Math.abs(distanceOffsetArray[j]- lastCheckOffset)&gt;1)||(j&gt;=(distanceOffsetArray.length- 2))){lastCheckOffset=distanceOffsetArray[j];scrollTimeouts[scrollTimeouts.length]=helpers.slowScrollHorizontalIntervalTimer(scrollIntervalTime*j,node,slideNodes,distanceOffsetArray[j],scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,newChildOffset,originalOffsets,childrenOffsets,infiniteSliderWidth,numberOfSlides,slideNodeOuterWidths,sliderNumber,centeredSlideOffset,endOffset,settings);}}
var slideChanged=false;var tempOffset=(newChildOffset+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if(settings.infiniteSlider){if(tempOffset!=activeChildInfOffsets[sliderNumber]){slideChanged=true;}}else{if(newChildOffset!=activeChildOffsets[sliderNumber]){slideChanged=true;}}
if(settings.onSlideComplete!=&#39;&#39;&amp;&amp;(distanceOffsetArray.length&gt;1)){scrollTimeouts[scrollTimeouts.length]=helpers.onSlideCompleteTimer(scrollIntervalTime*(j+ 1),settings,node,$(node).children(&#39;:eq(&#39;+ tempOffset+&#39;)&#39;),endOffset,sliderNumber);}
slideTimeouts[sliderNumber]=scrollTimeouts;helpers.hideScrollbar(settings,scrollTimeouts,j,distanceOffsetArray,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber);},onSlideComplete:function(settings,node,slideNode,newChildOffset,sliderNumber){var isChanged=(onChangeEventLastFired[sliderNumber]!=newChildOffset)?true:false;var args=new helpers.args(&#39;complete&#39;,settings,$(node),slideNode,newChildOffset,newChildOffset);$(node).parent().data(&#39;args&#39;,args);if(settings.onSlideComplete!=&#39;&#39;){settings.onSlideComplete(args);}
onChangeEventLastFired[sliderNumber]=newChildOffset;},getSliderOffset:function(node,xy){var sliderOffset=0;xy=(xy==&#39;x&#39;)?4:5;if(has3DTransform&amp;&amp;!isIe7&amp;&amp;!isIe8){var transforms=new Array(&#39;-webkit-transform&#39;,&#39;-moz-transform&#39;,&#39;transform&#39;);var transformArray;for(var i=0;i&lt;transforms.length;i++){if($(node).css(transforms[i])!=undefined){if($(node).css(transforms[i]).length&gt;0){transformArray=$(node).css(transforms[i]).split(&#39;,&#39;);break;}}}
sliderOffset=(transformArray[xy]==undefined)?0:parseInt(transformArray[xy],10);}else{sliderOffset=parseInt($(node).css(&#39;left&#39;),10);}
return sliderOffset;},setSliderOffset:function(node,sliderOffset){sliderOffset=parseInt(sliderOffset,10);if(has3DTransform&amp;&amp;!isIe7&amp;&amp;!isIe8){$(node).css({&#39;webkitTransform&#39;:&#39;matrix(1,0,0,1,&#39;+ sliderOffset+&#39;,0)&#39;,&#39;MozTransform&#39;:&#39;matrix(1,0,0,1,&#39;+ sliderOffset+&#39;,0)&#39;,&#39;transform&#39;:&#39;matrix(1,0,0,1,&#39;+ sliderOffset+&#39;,0)&#39;});}else{$(node).css({left:sliderOffset+&#39;px&#39;});}},setBrowserInfo:function(){if(navigator.userAgent.match(&#39;WebKit&#39;)!=null){isWebkit=true;grabOutCursor=&#39;-webkit-grab&#39;;grabInCursor=&#39;-webkit-grabbing&#39;;}else if(navigator.userAgent.match(&#39;Gecko&#39;)!=null){isGecko=true;grabOutCursor=&#39;move&#39;;grabInCursor=&#39;-moz-grabbing&#39;;}else if(navigator.userAgent.match(&#39;MSIE 7&#39;)!=null){isIe7=true;isIe=true;}else if(navigator.userAgent.match(&#39;MSIE 8&#39;)!=null){isIe8=true;isIe=true;}else if(navigator.userAgent.match(&#39;MSIE 9&#39;)!=null){isIe9=true;isIe=true;}},has3DTransform:function(){var has3D=false;var testElement=$(&#39;&lt;div /&gt;&#39;).css({&#39;webkitTransform&#39;:&#39;matrix(1,1,1,1,1,1)&#39;,&#39;MozTransform&#39;:&#39;matrix(1,1,1,1,1,1)&#39;,&#39;transform&#39;:&#39;matrix(1,1,1,1,1,1)&#39;});if(testElement.attr(&#39;style&#39;)==&#39;&#39;){has3D=false;}else if(isGecko&amp;&amp;(parseInt(navigator.userAgent.split(&#39;/&#39;)[3],10)&gt;=21)){has3D=false;}else if(testElement.attr(&#39;style&#39;)!=undefined){has3D=true;}
return has3D;},getSlideNumber:function(slide,sliderNumber,numberOfSlides){return(slide- infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;},calcActiveOffset:function(settings,offset,childrenOffsets,stageWidth,infiniteSliderOffset,numberOfSlides,activeChildOffset,sliderNumber){var isFirst=false;var arrayOfOffsets=new Array();var newChildOffset;if(offset&gt;childrenOffsets[0])newChildOffset=0;if(offset&lt;(childrenOffsets[childrenOffsets.length-1]))newChildOffset=numberOfSlides- 1;for(var i=0;i&lt;childrenOffsets.length;i++){if((childrenOffsets[i]&lt;=offset)&amp;&amp;(childrenOffsets[i]&gt;(offset- stageWidth))){if(!isFirst&amp;&amp;(childrenOffsets[i]!=offset)){arrayOfOffsets[arrayOfOffsets.length]=childrenOffsets[i-1];}
arrayOfOffsets[arrayOfOffsets.length]=childrenOffsets[i];isFirst=true;}}
if(arrayOfOffsets.length==0){arrayOfOffsets[0]=childrenOffsets[childrenOffsets.length- 1];}
var distance=stageWidth;var closestChildOffset=0;for(var i=0;i&lt;arrayOfOffsets.length;i++){var newDistance=Math.abs(offset- arrayOfOffsets[i]);if(newDistance&lt;distance){closestChildOffset=arrayOfOffsets[i];distance=newDistance;}}
for(var i=0;i&lt;childrenOffsets.length;i++){if(closestChildOffset==childrenOffsets[i]){newChildOffset=i;}}
return newChildOffset;},changeSlide:function(slide,node,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings){helpers.autoSlidePause(sliderNumber);for(var j=0;j&lt;scrollTimeouts.length;j++){clearTimeout(scrollTimeouts[j]);}
var steps=Math.ceil(settings.autoSlideTransTimer/10)+ 1;var startOffset=helpers.getSliderOffset(node,&#39;x&#39;);var endOffset=childrenOffsets[slide];var offsetDiff=endOffset- startOffset;var direction=slide-(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if(settings.infiniteSlider){slide=(slide- infiniteSliderOffset[sliderNumber]+ numberOfSlides*2)%numberOfSlides;var appendArray=false;if((slide==0)&amp;&amp;(numberOfSlides==2)){slide=numberOfSlides;childrenOffsets[slide]=childrenOffsets[slide-1]- $(slideNodes).eq(0).outerWidth(true);appendArray=true;}
endOffset=childrenOffsets[slide];offsetDiff=endOffset- startOffset;var offsets=new Array(childrenOffsets[slide]- $(node).width(),childrenOffsets[slide]+ $(node).width());if(appendArray){childrenOffsets.splice(childrenOffsets.length-1,1);}
for(var i=0;i&lt;offsets.length;i++){if(Math.abs(offsets[i]- startOffset)&lt;Math.abs(offsetDiff)){offsetDiff=(offsets[i]- startOffset);}}}
var stepArray=new Array();var t;var nextStep;helpers.showScrollbar(settings,scrollbarClass);for(var i=0;i&lt;=steps;i++){t=i;t/=steps;t--;nextStep=startOffset+ offsetDiff*(Math.pow(t,5)+ 1);stepArray[stepArray.length]=nextStep;}
var tempOffset=(slide+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;var lastCheckOffset=0;for(var i=0;i&lt;stepArray.length;i++){if((i==0)||(Math.abs(stepArray[i]- lastCheckOffset)&gt;1)||(i&gt;=(stepArray.length- 2))){lastCheckOffset=stepArray[i];scrollTimeouts[i]=helpers.slowScrollHorizontalIntervalTimer(scrollIntervalTime*(i+ 1),node,slideNodes,stepArray[i],scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,slide,originalOffsets,childrenOffsets,infiniteSliderWidth,numberOfSlides,slideNodeOuterWidths,sliderNumber,centeredSlideOffset,tempOffset,settings);}
if((i==0)&amp;&amp;(settings.onSlideStart!=&#39;&#39;)){var tempOffset2=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;settings.onSlideStart(new helpers.args(&#39;start&#39;,settings,node,$(node).children(&#39;:eq(&#39;+ tempOffset2+&#39;)&#39;),tempOffset2,slide));}}
var slideChanged=false;if(settings.infiniteSlider){if(tempOffset!=activeChildInfOffsets[sliderNumber]){slideChanged=true;}}else{if(slide!=activeChildOffsets[sliderNumber]){slideChanged=true;}}
if(slideChanged&amp;&amp;(settings.onSlideComplete!=&#39;&#39;)){scrollTimeouts[scrollTimeouts.length]=helpers.onSlideCompleteTimer(scrollIntervalTime*(i+ 1),settings,node,$(node).children(&#39;:eq(&#39;+ tempOffset+&#39;)&#39;),tempOffset,sliderNumber);}
slideTimeouts[sliderNumber]=scrollTimeouts;helpers.hideScrollbar(settings,scrollTimeouts,i,stepArray,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber);helpers.autoSlide(node,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);},autoSlide:function(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings){if(!iosSliderSettings[sliderNumber].autoSlide)return false;helpers.autoSlidePause(sliderNumber);autoSlideTimeouts[sliderNumber]=setTimeout(function(){if(!settings.infiniteSlider&amp;&amp;(activeChildOffsets[sliderNumber]&gt;childrenOffsets.length-1)){activeChildOffsets[sliderNumber]=activeChildOffsets[sliderNumber]- numberOfSlides;}
var nextSlide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ childrenOffsets.length+ 1)%childrenOffsets.length;helpers.changeSlide(nextSlide,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);helpers.autoSlide(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);},settings.autoSlideTimer+ settings.autoSlideTransTimer);},autoSlidePause:function(sliderNumber){clearTimeout(autoSlideTimeouts[sliderNumber]);},isUnselectable:function(node,settings){if(settings.unselectableSelector!=&#39;&#39;){if($(node).closest(settings.unselectableSelector).length==1)return true;}
return false;},slowScrollHorizontalIntervalTimer:function(scrollIntervalTime,node,slideNodes,step,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,slide,originalOffsets,childrenOffsets,infiniteSliderWidth,numberOfSlides,slideNodeOuterWidths,sliderNumber,centeredSlideOffset,endOffset,settings){var scrollTimeout=setTimeout(function(){helpers.slowScrollHorizontalInterval(node,slideNodes,step,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,slide,originalOffsets,childrenOffsets,infiniteSliderWidth,numberOfSlides,slideNodeOuterWidths,sliderNumber,centeredSlideOffset,endOffset,settings);},scrollIntervalTime);return scrollTimeout;},onSlideCompleteTimer:function(scrollIntervalTime,settings,node,slideNode,slide,scrollbarNumber){var scrollTimeout=setTimeout(function(){helpers.onSlideComplete(settings,node,slideNode,slide,scrollbarNumber);},scrollIntervalTime);return scrollTimeout;},hideScrollbarIntervalTimer:function(scrollIntervalTime,newOffset,opacity,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber,settings){var scrollTimeout=setTimeout(function(){helpers.hideScrollbarInterval(newOffset,opacity,scrollbarClass,scrollbarWidth,stageWidth,scrollMargin,scrollBorder,sliderNumber,settings);},scrollIntervalTime);return scrollTimeout;},args:function(func,settings,node,activeSlideNode,newChildOffset,targetSlideOffset){this.prevSlideNumber=($(node).parent().data(&#39;args&#39;)==undefined)?undefined:$(node).parent().data(&#39;args&#39;).prevSlideNumber;this.prevSlideObject=($(node).parent().data(&#39;args&#39;)==undefined)?undefined:$(node).parent().data(&#39;args&#39;).prevSlideObject;this.targetSlideNumber=targetSlideOffset+ 1;this.targetSlideObject=$(node).children(&#39;:eq(&#39;+ targetSlideOffset+&#39;)&#39;);this.slideChanged=false;if(func==&#39;load&#39;){this.targetSlideNumber=undefined;this.targetSlideObject=undefined;}else if(func==&#39;start&#39;){this.targetSlideNumber=undefined;this.targetSlideObject=undefined;}else if(func==&#39;change&#39;){this.slideChanged=true;this.prevSlideNumber=($(node).parent().data(&#39;args&#39;)==undefined)?settings.startAtSlide:$(node).parent().data(&#39;args&#39;).currentSlideNumber;this.prevSlideObject=$(node).children(&#39;:eq(&#39;+ this.prevSlideNumber+&#39;)&#39;);}else if(func==&#39;complete&#39;){this.slideChanged=$(node).parent().data(&#39;args&#39;).slideChanged;}
this.settings=settings;this.data=$(node).parent().data(&#39;iosslider&#39;);this.sliderObject=node;this.sliderContainerObject=$(node).parent();this.currentSlideObject=activeSlideNode;this.currentSlideNumber=newChildOffset+ 1;this.currentSliderOffset=helpers.getSliderOffset(node,&#39;x&#39;)*-1;},preventDrag:function(event){event.preventDefault();},preventClick:function(event){event.stopImmediatePropagation();return false;},enableClick:function(){return true;}}
helpers.setBrowserInfo();var methods={init:function(options,node){has3DTransform=helpers.has3DTransform();var settings=$.extend(true,{&#39;elasticPullResistance&#39;:0.6,&#39;frictionCoefficient&#39;:0.92,&#39;elasticFrictionCoefficient&#39;:0.6,&#39;snapFrictionCoefficient&#39;:0.92,&#39;snapToChildren&#39;:false,&#39;snapSlideCenter&#39;:false,&#39;startAtSlide&#39;:1,&#39;scrollbar&#39;:false,&#39;scrollbarDrag&#39;:false,&#39;scrollbarHide&#39;:true,&#39;scrollbarLocation&#39;:&#39;top&#39;,&#39;scrollbarContainer&#39;:&#39;&#39;,&#39;scrollbarOpacity&#39;:0.4,&#39;scrollbarHeight&#39;:&#39;4px&#39;,&#39;scrollbarBorder&#39;:&#39;0&#39;,&#39;scrollbarMargin&#39;:&#39;5px&#39;,&#39;scrollbarBackground&#39;:&#39;#000&#39;,&#39;scrollbarBorderRadius&#39;:&#39;100px&#39;,&#39;scrollbarShadow&#39;:&#39;0 0 0 #000&#39;,&#39;scrollbarElasticPullResistance&#39;:0.9,&#39;desktopClickDrag&#39;:false,&#39;keyboardControls&#39;:false,&#39;tabToAdvance&#39;:false,&#39;responsiveSlideContainer&#39;:true,&#39;responsiveSlides&#39;:true,&#39;navSlideSelector&#39;:&#39;&#39;,&#39;navPrevSelector&#39;:&#39;&#39;,&#39;navNextSelector&#39;:&#39;&#39;,&#39;autoSlideToggleSelector&#39;:&#39;&#39;,&#39;autoSlide&#39;:false,&#39;autoSlideTimer&#39;:5000,&#39;autoSlideTransTimer&#39;:750,&#39;autoSlideHoverPause&#39;:true,&#39;infiniteSlider&#39;:false,&#39;snapVelocityThreshold&#39;:5,&#39;slideStartVelocityThreshold&#39;:0,&#39;horizontalSlideLockThreshold&#39;:5,&#39;verticalSlideLockThreshold&#39;:3,&#39;stageCSS&#39;:{position:&#39;relative&#39;,top:&#39;0&#39;,left:&#39;0&#39;,overflow:&#39;hidden&#39;,zIndex:1},&#39;unselectableSelector&#39;:&#39;&#39;,&#39;onSliderLoaded&#39;:&#39;&#39;,&#39;onSliderUpdate&#39;:&#39;&#39;,&#39;onSliderResize&#39;:&#39;&#39;,&#39;onSlideStart&#39;:&#39;&#39;,&#39;onSlideChange&#39;:&#39;&#39;,&#39;onSlideComplete&#39;:&#39;&#39;},options);if(node==undefined){node=this;}
return $(node).each(function(i){scrollbarNumber++;var sliderNumber=scrollbarNumber;var scrollTimeouts=new Array();iosSliderSettings[sliderNumber]=$.extend({},settings);sliderMin[sliderNumber]=0;sliderMax[sliderNumber]=0;var minTouchpoints=0;var xCurrentScrollRate=new Array(0,0);var yCurrentScrollRate=new Array(0,0);var scrollbarBlockClass=&#39;scrollbarBlock&#39;+ scrollbarNumber;var scrollbarClass=&#39;scrollbar&#39;+ scrollbarNumber;var scrollbarNode;var scrollbarBlockNode;var scrollbarStageWidth;var scrollbarWidth;var containerWidth;var containerHeight;var centeredSlideOffset=0;var stageNode=$(this);var stageWidth;var stageHeight;var slideWidth;var scrollMargin;var scrollBorder;var lastTouch;var isFirstInit=true;var newChildOffset=-1;var webkitTransformArray=new Array();var childrenOffsets;var originalOffsets=new Array();var scrollbarStartOpacity=0;var xScrollStartPosition=0;var yScrollStartPosition=0;var currentTouches=0;var scrollerNode=$(this).children(&#39;:first-child&#39;);var slideNodes;var slideNodeWidths;var slideNodeOuterWidths;var numberOfSlides=$(scrollerNode).children().not(&#39;script&#39;).length;var xScrollStarted=false;var lastChildOffset=0;var isMouseDown=false;var currentSlider=undefined;var sliderStopLocation=0;var infiniteSliderWidth;infiniteSliderOffset[sliderNumber]=0;var shortContent=false;onChangeEventLastFired[sliderNumber]=-1;var isAutoSlideToggleOn=false;iosSliders[sliderNumber]=stageNode;isEventCleared[sliderNumber]=false;var currentEventNode;var intermediateChildOffset=0;var tempInfiniteSliderOffset=0;var preventXScroll=false;var snapOverride=false;var clickEvent=&#39;touchstart.iosSliderEvent click.iosSliderEvent&#39;;var scrollerWidth;var anchorEvents;var onclickEvents;var allScrollerNodeChildren;touchLocks[sliderNumber]=false;slideTimeouts[sliderNumber]=new Array();if(settings.scrollbarDrag){settings.scrollbar=true;settings.scrollbarHide=false;}
var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if(data!=undefined)return true;var xArray=[&#39;d&#39;,&#39;e&#39;,&#39;m&#39;,&#39;o&#39;,&#39; &#39;,&#39;v&#39;,&#39;e&#39;,&#39;r&#39;,&#39;s&#39;,&#39;i&#39;,&#39;o&#39;,&#39;n&#39;];var xClass=Math.floor(Math.random()*12317);$(scrollerNode).parent().append(&quot;&lt;i class = &#39;i&quot;+ xClass+&quot;&#39;&gt;&lt;/i&gt;&quot;).append(&quot;&lt;i class = &#39;i&quot;+ xClass+&quot;&#39;&gt;&lt;/i&gt;&quot;);$(&#39;.i&#39;+ xClass).css({position:&#39;absolute&#39;,right:&#39;10px&#39;,bottom:&#39;10px&#39;,zIndex:1000,fontStyle:&#39;normal&#39;,background:&#39;#fff&#39;,opacity:0.2}).eq(1).css({bottom:&#39;auto&#39;,right:&#39;auto&#39;,top:&#39;10px&#39;,left:&#39;10px&#39;});for(var i=0;i&lt;xArray.length;i++){$(&#39;.i&#39;+ xClass).html($(&#39;.i&#39;+ xClass).html()+ xArray[i]);}
$(this).find(&#39;img&#39;).bind(&#39;dragstart.iosSliderEvent&#39;,function(event){event.preventDefault();});if(settings.infiniteSlider){settings.scrollbar=false;}
if(settings.infiniteSlider&amp;&amp;(numberOfSlides==1)){settings.infiniteSlider=false;}
if(settings.scrollbar){if(settings.scrollbarContainer!=&#39;&#39;){$(settings.scrollbarContainer).append(&quot;&lt;div class = &#39;&quot;+ scrollbarBlockClass+&quot;&#39;&gt;&lt;div class = &#39;&quot;+ scrollbarClass+&quot;&#39;&gt;&lt;/div&gt;&lt;/div&gt;&quot;);}else{$(scrollerNode).parent().append(&quot;&lt;div class = &#39;&quot;+ scrollbarBlockClass+&quot;&#39;&gt;&lt;div class = &#39;&quot;+ scrollbarClass+&quot;&#39;&gt;&lt;/div&gt;&lt;/div&gt;&quot;);}}
if(!init())return true;$(this).find(&#39;a&#39;).bind(&#39;mousedown&#39;,helpers.preventDrag);$(this).find(&quot;[onclick]&quot;).bind(&#39;click&#39;,helpers.preventDrag).each(function(){$(this).data(&#39;onclick&#39;,this.onclick);});var newChildOffset=helpers.calcActiveOffset(settings,helpers.getSliderOffset($(scrollerNode),&#39;x&#39;),childrenOffsets,stageWidth,infiniteSliderOffset[sliderNumber],numberOfSlides,undefined,sliderNumber);var tempOffset=(newChildOffset+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;var args=new helpers.args(&#39;load&#39;,settings,scrollerNode,$(scrollerNode).children(&#39;:eq(&#39;+ tempOffset+&#39;)&#39;),tempOffset,tempOffset);$(stageNode).data(&#39;args&#39;,args);if(settings.onSliderLoaded!=&#39;&#39;){settings.onSliderLoaded(args);}
onChangeEventLastFired[sliderNumber]=tempOffset;function init(){helpers.autoSlidePause(sliderNumber);anchorEvents=$(scrollerNode).find(&#39;a&#39;);onclickEvents=$(scrollerNode).find(&#39;[onclick]&#39;);allScrollerNodeChildren=$(scrollerNode).find(&#39;*&#39;);$(stageNode).css(&#39;width&#39;,&#39;&#39;);$(stageNode).css(&#39;height&#39;,&#39;&#39;);$(scrollerNode).css(&#39;width&#39;,&#39;&#39;);slideNodes=$(scrollerNode).children().not(&#39;script&#39;).get();slideNodeWidths=new Array();slideNodeOuterWidths=new Array();if(settings.responsiveSlides){$(slideNodes).css(&#39;width&#39;,&#39;&#39;);}
sliderMax[sliderNumber]=0;childrenOffsets=new Array();containerWidth=$(stageNode).parent().width();stageWidth=$(stageNode).outerWidth(true);if(settings.responsiveSlideContainer){stageWidth=($(stageNode).outerWidth(true)&gt;containerWidth)?containerWidth:$(stageNode).width();}
$(stageNode).css({position:settings.stageCSS.position,top:settings.stageCSS.top,left:settings.stageCSS.left,overflow:settings.stageCSS.overflow,zIndex:settings.stageCSS.zIndex,&#39;webkitPerspective&#39;:1000,&#39;webkitBackfaceVisibility&#39;:&#39;hidden&#39;,&#39;msTouchAction&#39;:&#39;pan-y&#39;,width:stageWidth});$(settings.unselectableSelector).css({cursor:&#39;default&#39;});for(var j=0;j&lt;slideNodes.length;j++){slideNodeWidths[j]=$(slideNodes[j]).width();slideNodeOuterWidths[j]=$(slideNodes[j]).outerWidth(true);var newWidth=slideNodeOuterWidths[j];if(settings.responsiveSlides){if(slideNodeOuterWidths[j]&gt;stageWidth){newWidth=stageWidth+(slideNodeOuterWidths[j]- slideNodeWidths[j])*-1;slideNodeWidths[j]=newWidth;slideNodeOuterWidths[j]=stageWidth;}else{newWidth=slideNodeWidths[j];}
$(slideNodes[j]).css({width:newWidth});}
$(slideNodes[j]).css({&#39;webkitBackfaceVisibility&#39;:&#39;hidden&#39;,overflow:&#39;hidden&#39;,position:&#39;absolute&#39;});childrenOffsets[j]=sliderMax[sliderNumber]*-1;sliderMax[sliderNumber]=sliderMax[sliderNumber]+ newWidth+(slideNodeOuterWidths[j]- slideNodeWidths[j]);}
if(settings.snapSlideCenter){centeredSlideOffset=(stageWidth- slideNodeOuterWidths[0])*0.5;if(settings.responsiveSlides&amp;&amp;(slideNodeOuterWidths[0]&gt;stageWidth)){centeredSlideOffset=0;}}
sliderAbsMax[sliderNumber]=sliderMax[sliderNumber]*2;for(var j=0;j&lt;slideNodes.length;j++){helpers.setSliderOffset($(slideNodes[j]),childrenOffsets[j]*-1+ sliderMax[sliderNumber]+ centeredSlideOffset);childrenOffsets[j]=childrenOffsets[j]- sliderMax[sliderNumber];}
if(!settings.infiniteSlider&amp;&amp;!settings.snapSlideCenter){for(var i=0;i&lt;childrenOffsets.length;i++){if(childrenOffsets[i]&lt;=((sliderMax[sliderNumber]*2- stageWidth)*-1)){break;}
lastChildOffset=i;}
childrenOffsets.splice(lastChildOffset+ 1,childrenOffsets.length);childrenOffsets[childrenOffsets.length]=(sliderMax[sliderNumber]*2- stageWidth)*-1;}
for(var i=0;i&lt;childrenOffsets.length;i++){originalOffsets[i]=childrenOffsets[i];}
if(isFirstInit){iosSliderSettings[sliderNumber].startAtSlide=(iosSliderSettings[sliderNumber].startAtSlide&gt;childrenOffsets.length)?childrenOffsets.length:iosSliderSettings[sliderNumber].startAtSlide;if(settings.infiniteSlider){iosSliderSettings[sliderNumber].startAtSlide=(iosSliderSettings[sliderNumber].startAtSlide- 1+ numberOfSlides)%numberOfSlides;activeChildOffsets[sliderNumber]=(iosSliderSettings[sliderNumber].startAtSlide);}else{iosSliderSettings[sliderNumber].startAtSlide=((iosSliderSettings[sliderNumber].startAtSlide- 1)&lt;0)?childrenOffsets.length-1:iosSliderSettings[sliderNumber].startAtSlide;activeChildOffsets[sliderNumber]=(iosSliderSettings[sliderNumber].startAtSlide-1);}
activeChildInfOffsets[sliderNumber]=activeChildOffsets[sliderNumber];}
sliderMin[sliderNumber]=sliderMax[sliderNumber]+ centeredSlideOffset;$(scrollerNode).css({position:&#39;relative&#39;,cursor:grabOutCursor,&#39;webkitPerspective&#39;:&#39;0&#39;,&#39;webkitBackfaceVisibility&#39;:&#39;hidden&#39;,width:sliderMax[sliderNumber]+&#39;px&#39;});scrollerWidth=sliderMax[sliderNumber];sliderMax[sliderNumber]=sliderMax[sliderNumber]*2- stageWidth+ centeredSlideOffset*2;shortContent=(((scrollerWidth+ centeredSlideOffset)&lt;stageWidth)||(stageWidth==0))?true:false;if(shortContent){$(scrollerNode).css({cursor:&#39;default&#39;});}
containerHeight=$(stageNode).parent().outerHeight(true);stageHeight=$(stageNode).height();if(settings.responsiveSlideContainer){stageHeight=(stageHeight&gt;containerHeight)?containerHeight:stageHeight;}
$(stageNode).css({height:stageHeight});helpers.setSliderOffset(scrollerNode,childrenOffsets[activeChildOffsets[sliderNumber]]);if(settings.infiniteSlider&amp;&amp;!shortContent){var currentScrollOffset=helpers.getSliderOffset($(scrollerNode),&#39;x&#39;);var count=(infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides*-1;while(count&lt;0){var lowSlideNumber=0;var lowSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&lt;lowSlideOffset){lowSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);lowSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]+ scrollerWidth;helpers.setSliderOffset($(slideNodes)[lowSlideNumber],newOffset);sliderMin[sliderNumber]=childrenOffsets[1]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;childrenOffsets.splice(0,1);childrenOffsets.splice(childrenOffsets.length,0,newOffset*-1+ centeredSlideOffset);count++;}
while(((childrenOffsets[0]*-1- scrollerWidth+ centeredSlideOffset)&gt;0)&amp;&amp;settings.snapSlideCenter&amp;&amp;isFirstInit){var highSlideNumber=0;var highSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&gt;highSlideOffset){highSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);highSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]- slideNodeOuterWidths[highSlideNumber];helpers.setSliderOffset($(slideNodes)[highSlideNumber],newOffset);childrenOffsets.splice(0,0,newOffset*-1+ centeredSlideOffset);childrenOffsets.splice(childrenOffsets.length-1,1);sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]--;activeChildOffsets[sliderNumber]++;}
while(currentScrollOffset&lt;=(sliderMax[sliderNumber]*-1)){var lowSlideNumber=0;var lowSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&lt;lowSlideOffset){lowSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);lowSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]+ scrollerWidth;helpers.setSliderOffset($(slideNodes)[lowSlideNumber],newOffset);sliderMin[sliderNumber]=childrenOffsets[1]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;childrenOffsets.splice(0,1);childrenOffsets.splice(childrenOffsets.length,0,newOffset*-1+ centeredSlideOffset);infiniteSliderOffset[sliderNumber]++;activeChildOffsets[sliderNumber]--;}}
helpers.setSliderOffset(scrollerNode,childrenOffsets[activeChildOffsets[sliderNumber]]);if(!settings.desktopClickDrag){$(scrollerNode).css({cursor:&#39;default&#39;});}
if(settings.scrollbar){$(&#39;.&#39;+ scrollbarBlockClass).css({margin:settings.scrollbarMargin,overflow:&#39;hidden&#39;,display:&#39;none&#39;});$(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass).css({border:settings.scrollbarBorder});scrollMargin=parseInt($(&#39;.&#39;+ scrollbarBlockClass).css(&#39;marginLeft&#39;))+ parseInt($(&#39;.&#39;+ scrollbarBlockClass).css(&#39;marginRight&#39;));scrollBorder=parseInt($(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass).css(&#39;borderLeftWidth&#39;),10)+ parseInt($(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass).css(&#39;borderRightWidth&#39;),10);scrollbarStageWidth=(settings.scrollbarContainer!=&#39;&#39;)?$(settings.scrollbarContainer).width():stageWidth;scrollbarWidth=(stageWidth/scrollerWidth)*(scrollbarStageWidth- scrollMargin);if(!settings.scrollbarHide){scrollbarStartOpacity=settings.scrollbarOpacity;}
$(&#39;.&#39;+ scrollbarBlockClass).css({position:&#39;absolute&#39;,left:0,width:scrollbarStageWidth- scrollMargin+&#39;px&#39;,margin:settings.scrollbarMargin});if(settings.scrollbarLocation==&#39;top&#39;){$(&#39;.&#39;+ scrollbarBlockClass).css(&#39;top&#39;,&#39;0&#39;);}else{$(&#39;.&#39;+ scrollbarBlockClass).css(&#39;bottom&#39;,&#39;0&#39;);}
$(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass).css({borderRadius:settings.scrollbarBorderRadius,background:settings.scrollbarBackground,height:settings.scrollbarHeight,width:scrollbarWidth- scrollBorder+&#39;px&#39;,minWidth:settings.scrollbarHeight,border:settings.scrollbarBorder,&#39;webkitPerspective&#39;:1000,&#39;webkitBackfaceVisibility&#39;:&#39;hidden&#39;,&#39;position&#39;:&#39;relative&#39;,opacity:scrollbarStartOpacity,filter:&#39;alpha(opacity:&#39;+(scrollbarStartOpacity*100)+&#39;)&#39;,boxShadow:settings.scrollbarShadow});helpers.setSliderOffset($(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass),Math.floor((childrenOffsets[activeChildOffsets[sliderNumber]]*-1- sliderMin[sliderNumber]+ centeredSlideOffset)/ (sliderMax[sliderNumber] - sliderMin[sliderNumber] + centeredSlideOffset) * (scrollbarStageWidth - scrollMargin - scrollbarWidth)));
$(&#39;.&#39;+ scrollbarBlockClass).css({display:&#39;block&#39;});scrollbarNode=$(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass);scrollbarBlockNode=$(&#39;.&#39;+ scrollbarBlockClass);}
if(settings.scrollbarDrag&amp;&amp;!shortContent){$(&#39;.&#39;+ scrollbarBlockClass+&#39; .&#39;+ scrollbarClass).css({cursor:grabOutCursor});}
if(settings.infiniteSlider){infiniteSliderWidth=(sliderMax[sliderNumber]+ stageWidth)/ 3;
}
if(settings.navSlideSelector!=&#39;&#39;){$(settings.navSlideSelector).each(function(j){$(this).css({cursor:&#39;pointer&#39;});$(this).unbind(clickEvent).bind(clickEvent,function(e){if(e.type==&#39;touchstart&#39;){$(this).unbind(&#39;click.iosSliderEvent&#39;);}else{$(this).unbind(&#39;touchstart.iosSliderEvent&#39;);}
clickEvent=e.type+&#39;.iosSliderEvent&#39;;helpers.changeSlide(j,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);});});}
if(settings.navPrevSelector!=&#39;&#39;){$(settings.navPrevSelector).css({cursor:&#39;pointer&#39;});$(settings.navPrevSelector).unbind(clickEvent).bind(clickEvent,function(e){if(e.type==&#39;touchstart&#39;){$(this).unbind(&#39;click.iosSliderEvent&#39;);}else{$(this).unbind(&#39;touchstart.iosSliderEvent&#39;);}
clickEvent=e.type+&#39;.iosSliderEvent&#39;;var slide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if((slide&gt;0)||settings.infiniteSlider){helpers.changeSlide(slide- 1,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);}});}
if(settings.navNextSelector!=&#39;&#39;){$(settings.navNextSelector).css({cursor:&#39;pointer&#39;});$(settings.navNextSelector).unbind(clickEvent).bind(clickEvent,function(e){if(e.type==&#39;touchstart&#39;){$(this).unbind(&#39;click.iosSliderEvent&#39;);}else{$(this).unbind(&#39;touchstart.iosSliderEvent&#39;);}
clickEvent=e.type+&#39;.iosSliderEvent&#39;;var slide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if((slide&lt;childrenOffsets.length-1)||settings.infiniteSlider){helpers.changeSlide(slide+ 1,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);}});}
if(settings.autoSlide&amp;&amp;!shortContent){if(settings.autoSlideToggleSelector!=&#39;&#39;){$(settings.autoSlideToggleSelector).css({cursor:&#39;pointer&#39;});$(settings.autoSlideToggleSelector).unbind(clickEvent).bind(clickEvent,function(e){if(e.type==&#39;touchstart&#39;){$(this).unbind(&#39;click.iosSliderEvent&#39;);}else{$(this).unbind(&#39;touchstart.iosSliderEvent&#39;);}
clickEvent=e.type+&#39;.iosSliderEvent&#39;;if(!isAutoSlideToggleOn){helpers.autoSlidePause(sliderNumber);isAutoSlideToggleOn=true;$(settings.autoSlideToggleSelector).addClass(&#39;on&#39;);}else{helpers.autoSlide(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);isAutoSlideToggleOn=false;$(settings.autoSlideToggleSelector).removeClass(&#39;on&#39;);}});}}
helpers.autoSlide(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);$(stageNode).bind(&#39;mouseleave.iosSliderEvent&#39;,function(){if(isAutoSlideToggleOn)return true;helpers.autoSlide(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);});$(stageNode).bind(&#39;touchend.iosSliderEvent&#39;,function(){if(isAutoSlideToggleOn)return true;helpers.autoSlide(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);});if(settings.autoSlideHoverPause){$(stageNode).bind(&#39;mouseenter.iosSliderEvent&#39;,function(){helpers.autoSlidePause(sliderNumber);});}
$(stageNode).data(&#39;iosslider&#39;,{obj:$this,settings:settings,scrollerNode:scrollerNode,slideNodes:slideNodes,numberOfSlides:numberOfSlides,centeredSlideOffset:centeredSlideOffset,sliderNumber:sliderNumber,originalOffsets:originalOffsets,childrenOffsets:childrenOffsets,sliderMax:sliderMax[sliderNumber],scrollbarClass:scrollbarClass,scrollbarWidth:scrollbarWidth,scrollbarStageWidth:scrollbarStageWidth,stageWidth:stageWidth,scrollMargin:scrollMargin,scrollBorder:scrollBorder,infiniteSliderOffset:infiniteSliderOffset[sliderNumber],infiniteSliderWidth:infiniteSliderWidth,slideNodeOuterWidths:slideNodeOuterWidths,shortContent:shortContent});isFirstInit=false;return true;}
if(iosSliderSettings[sliderNumber].responsiveSlides||iosSliderSettings[sliderNumber].responsiveSlideContainer){var orientationEvent=supportsOrientationChange?&#39;orientationchange&#39;:&#39;resize&#39;;$(window).bind(orientationEvent+&#39;.iosSliderEvent-&#39;+ sliderNumber,function(){if(!init())return true;var args=$(stageNode).data(&#39;args&#39;);if(settings.onSliderResize!=&#39;&#39;){settings.onSliderResize(args);}});}
if((settings.keyboardControls||settings.tabToAdvance)&amp;&amp;!shortContent){$(document).bind(&#39;keydown.iosSliderEvent&#39;,function(e){if((!isIe7)&amp;&amp;(!isIe8)){var e=e.originalEvent;}
if(touchLocks[sliderNumber])return true;if((e.keyCode==37)&amp;&amp;settings.keyboardControls){e.preventDefault();var slide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if((slide&gt;0)||settings.infiniteSlider){helpers.changeSlide(slide- 1,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);}}else if(((e.keyCode==39)&amp;&amp;settings.keyboardControls)||((e.keyCode==9)&amp;&amp;settings.tabToAdvance)){e.preventDefault();var slide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if((slide&lt;childrenOffsets.length-1)||settings.infiniteSlider){helpers.changeSlide(slide+ 1,scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,centeredSlideOffset,settings);}}});}
if(isTouch||settings.desktopClickDrag){var touchStartFlag=false;var touchSelection=$(scrollerNode);var touchSelectionMove=$(scrollerNode);var preventDefault=null;var isUnselectable=false;if(settings.scrollbarDrag){touchSelection=touchSelection.add(scrollbarNode);touchSelectionMove=touchSelectionMove.add(scrollbarBlockNode);}
$(touchSelection).bind(&#39;mousedown.iosSliderEvent touchstart.iosSliderEvent&#39;,function(e){if(touchStartFlag)return true;touchStartFlag=true;if(e.type==&#39;touchstart&#39;){$(touchSelectionMove).unbind(&#39;mousedown.iosSliderEvent&#39;);}else{$(touchSelectionMove).unbind(&#39;touchstart.iosSliderEvent&#39;);}
if(touchLocks[sliderNumber]||shortContent){touchStartFlag=false;xScrollStarted=false;return true;}
isUnselectable=helpers.isUnselectable(e.target,settings);if(isUnselectable){touchStartFlag=false;xScrollStarted=false;return true;}
currentEventNode=($(this)[0]===$(scrollbarNode)[0])?scrollbarNode:scrollerNode;if((!isIe7)&amp;&amp;(!isIe8)){var e=e.originalEvent;}
helpers.autoSlidePause(sliderNumber);allScrollerNodeChildren.unbind(&#39;.disableClick&#39;);if(e.type==&#39;touchstart&#39;){eventX=e.touches[0].pageX;eventY=e.touches[0].pageY;}else{if(window.getSelection){if(window.getSelection().empty){window.getSelection().empty();}else if(window.getSelection().removeAllRanges){window.getSelection().removeAllRanges();}}else if(document.selection){if(isIe8){try{document.selection.empty();}catch(e){}}else{document.selection.empty();}}
eventX=e.pageX;eventY=e.pageY;isMouseDown=true;currentSlider=scrollerNode;$(this).css({cursor:grabInCursor});}
xCurrentScrollRate=new Array(0,0);yCurrentScrollRate=new Array(0,0);xScrollDistance=0;xScrollStarted=false;for(var j=0;j&lt;scrollTimeouts.length;j++){clearTimeout(scrollTimeouts[j]);}
var scrollPosition=helpers.getSliderOffset(scrollerNode,&#39;x&#39;);if(scrollPosition&gt;(sliderMin[sliderNumber]*-1+ centeredSlideOffset+ scrollerWidth)){scrollPosition=sliderMin[sliderNumber]*-1+ centeredSlideOffset+ scrollerWidth;helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),scrollPosition);$(&#39;.&#39;+ scrollbarClass).css({width:(scrollbarWidth- scrollBorder)+&#39;px&#39;});}else if(scrollPosition&lt;(sliderMax[sliderNumber]*-1)){scrollPosition=sliderMax[sliderNumber]*-1;helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),(scrollbarStageWidth- scrollMargin- scrollbarWidth));$(&#39;.&#39;+ scrollbarClass).css({width:(scrollbarWidth- scrollBorder)+&#39;px&#39;});}
var scrollbarSubtractor=($(this)[0]===$(scrollbarNode)[0])?(sliderMin[sliderNumber]):0;xScrollStartPosition=(helpers.getSliderOffset(this,&#39;x&#39;)- eventX- scrollbarSubtractor)*-1;yScrollStartPosition=(helpers.getSliderOffset(this,&#39;y&#39;)- eventY)*-1;xCurrentScrollRate[1]=eventX;yCurrentScrollRate[1]=eventY;snapOverride=false;});$(document).bind(&#39;touchmove.iosSliderEvent mousemove.iosSliderEvent&#39;,function(e){if((!isIe7)&amp;&amp;(!isIe8)){var e=e.originalEvent;}
if(touchLocks[sliderNumber]||shortContent||isUnselectable||!touchStartFlag)return true;var edgeDegradation=0;if(e.type==&#39;touchmove&#39;){eventX=e.touches[0].pageX;eventY=e.touches[0].pageY;}else{if(window.getSelection){if(window.getSelection().empty){}else if(window.getSelection().removeAllRanges){window.getSelection().removeAllRanges();}}else if(document.selection){if(isIe8){try{document.selection.empty();}catch(e){}}else{document.selection.empty();}}
eventX=e.pageX;eventY=e.pageY;if(!isMouseDown){return true;}
if(!isIe){if((typeof e.webkitMovementX!=&#39;undefined&#39;||typeof e.webkitMovementY!=&#39;undefined&#39;)&amp;&amp;e.webkitMovementY===0&amp;&amp;e.webkitMovementX===0){return true;}}}
xCurrentScrollRate[0]=xCurrentScrollRate[1];xCurrentScrollRate[1]=eventX;xScrollDistance=(xCurrentScrollRate[1]- xCurrentScrollRate[0])/ 2;
yCurrentScrollRate[0]=yCurrentScrollRate[1];yCurrentScrollRate[1]=eventY;yScrollDistance=(yCurrentScrollRate[1]- yCurrentScrollRate[0])/ 2;
if(!xScrollStarted){var slide=(activeChildOffsets[sliderNumber]+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;var args=new helpers.args(&#39;start&#39;,settings,scrollerNode,$(scrollerNode).children(&#39;:eq(&#39;+ slide+&#39;)&#39;),slide,undefined);$(stageNode).data(&#39;args&#39;,args);if(settings.onSlideStart!=&#39;&#39;){settings.onSlideStart(args);}}
if(((yScrollDistance&gt;settings.verticalSlideLockThreshold)||(yScrollDistance&lt;(settings.verticalSlideLockThreshold*-1)))&amp;&amp;(e.type==&#39;touchmove&#39;)&amp;&amp;(!xScrollStarted)){preventXScroll=true;}
if(((xScrollDistance&gt;settings.horizontalSlideLockThreshold)||(xScrollDistance&lt;(settings.horizontalSlideLockThreshold*-1)))&amp;&amp;(e.type==&#39;touchmove&#39;)){e.preventDefault();}
if(((xScrollDistance&gt;settings.slideStartVelocityThreshold)||(xScrollDistance&lt;(settings.slideStartVelocityThreshold*-1)))){xScrollStarted=true;}
if(xScrollStarted&amp;&amp;!preventXScroll){var scrollPosition=helpers.getSliderOffset(scrollerNode,&#39;x&#39;);var scrollbarSubtractor=($(currentEventNode)[0]===$(scrollbarNode)[0])?(sliderMin[sliderNumber]):centeredSlideOffset;var scrollbarMultiplier=($(currentEventNode)[0]===$(scrollbarNode)[0])?((sliderMin[sliderNumber]- sliderMax[sliderNumber]- centeredSlideOffset)/ (scrollbarStageWidth - scrollMargin - scrollbarWidth)) : 1;
var elasticPullResistance=($(currentEventNode)[0]===$(scrollbarNode)[0])?settings.scrollbarElasticPullResistance:settings.elasticPullResistance;var snapCenteredSlideOffset=(settings.snapSlideCenter&amp;&amp;($(currentEventNode)[0]===$(scrollbarNode)[0]))?0:centeredSlideOffset;var snapCenteredSlideOffsetScrollbar=(settings.snapSlideCenter&amp;&amp;($(currentEventNode)[0]===$(scrollbarNode)[0]))?centeredSlideOffset:0;if(e.type==&#39;touchmove&#39;){if(currentTouches!=e.touches.length){xScrollStartPosition=(scrollPosition*-1)+ eventX;}
currentTouches=e.touches.length;}
if(settings.infiniteSlider){if(scrollPosition&lt;=(sliderMax[sliderNumber]*-1)){var scrollerWidth=$(scrollerNode).width();if(scrollPosition&lt;=(sliderAbsMax[sliderNumber]*-1)){var sum=originalOffsets[0]*-1;$(slideNodes).each(function(i){helpers.setSliderOffset($(slideNodes)[i],sum+ centeredSlideOffset);if(i&lt;childrenOffsets.length){childrenOffsets[i]=sum*-1;}
sum=sum+ slideNodeOuterWidths[i];});xScrollStartPosition=xScrollStartPosition- childrenOffsets[0]*-1;sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]=0;}else{var lowSlideNumber=0;var lowSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&lt;lowSlideOffset){lowSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);lowSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]+ scrollerWidth;helpers.setSliderOffset($(slideNodes)[lowSlideNumber],newOffset);sliderMin[sliderNumber]=childrenOffsets[1]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;childrenOffsets.splice(0,1);childrenOffsets.splice(childrenOffsets.length,0,newOffset*-1+ centeredSlideOffset);infiniteSliderOffset[sliderNumber]++;}}
if((scrollPosition&gt;=(sliderMin[sliderNumber]*-1))||(scrollPosition&gt;=0)){var scrollerWidth=$(scrollerNode).width();if(scrollPosition&gt;=0){var sum=originalOffsets[0]*-1;$(slideNodes).each(function(i){helpers.setSliderOffset($(slideNodes)[i],sum+ centeredSlideOffset);if(i&lt;childrenOffsets.length){childrenOffsets[i]=sum*-1;}
sum=sum+ slideNodeOuterWidths[i];});xScrollStartPosition=xScrollStartPosition+ childrenOffsets[0]*-1;sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]=numberOfSlides;while(((childrenOffsets[0]*-1- scrollerWidth+ centeredSlideOffset)&gt;0)){var highSlideNumber=0;var highSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&gt;highSlideOffset){highSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);highSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]- slideNodeOuterWidths[highSlideNumber];helpers.setSliderOffset($(slideNodes)[highSlideNumber],newOffset);childrenOffsets.splice(0,0,newOffset*-1+ centeredSlideOffset);childrenOffsets.splice(childrenOffsets.length-1,1);sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]--;activeChildOffsets[sliderNumber]++;}}else{var highSlideNumber=0;var highSlideOffset=helpers.getSliderOffset($(slideNodes[0]),&#39;x&#39;);$(slideNodes).each(function(i){if(helpers.getSliderOffset(this,&#39;x&#39;)&gt;highSlideOffset){highSlideOffset=helpers.getSliderOffset(this,&#39;x&#39;);highSlideNumber=i;}});var newOffset=sliderMin[sliderNumber]- slideNodeOuterWidths[highSlideNumber];helpers.setSliderOffset($(slideNodes)[highSlideNumber],newOffset);childrenOffsets.splice(0,0,newOffset*-1+ centeredSlideOffset);childrenOffsets.splice(childrenOffsets.length-1,1);sliderMin[sliderNumber]=childrenOffsets[0]*-1+ centeredSlideOffset;sliderMax[sliderNumber]=sliderMin[sliderNumber]+ scrollerWidth- stageWidth;infiniteSliderOffset[sliderNumber]--;}}}else{var scrollerWidth=$(scrollerNode).width();if(scrollPosition&gt;(sliderMin[sliderNumber]*-1+ centeredSlideOffset)){edgeDegradation=(sliderMin[sliderNumber]+((xScrollStartPosition- scrollbarSubtractor- eventX+ snapCenteredSlideOffset)*-1*scrollbarMultiplier)- scrollbarSubtractor)*elasticPullResistance*-1/scrollbarMultiplier;}
if(scrollPosition&lt;(sliderMax[sliderNumber]*-1)){edgeDegradation=(sliderMax[sliderNumber]+ snapCenteredSlideOffsetScrollbar+((xScrollStartPosition- scrollbarSubtractor- eventX)*-1*scrollbarMultiplier)- scrollbarSubtractor)*elasticPullResistance*-1/scrollbarMultiplier;}}
helpers.setSliderOffset(scrollerNode,((xScrollStartPosition- scrollbarSubtractor- eventX- edgeDegradation)*-1*scrollbarMultiplier)- scrollbarSubtractor+ snapCenteredSlideOffsetScrollbar);if(settings.scrollbar){helpers.showScrollbar(settings,scrollbarClass);scrollbarDistance=Math.floor((xScrollStartPosition- eventX- edgeDegradation- sliderMin[sliderNumber]+ snapCenteredSlideOffset)/ (sliderMax[sliderNumber] - sliderMin[sliderNumber] + centeredSlideOffset) * (scrollbarStageWidth - scrollMargin - scrollbarWidth) * scrollbarMultiplier);
var width=scrollbarWidth;if(scrollbarDistance&lt;=0){width=scrollbarWidth- scrollBorder-(scrollbarDistance*-1);helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),0);$(&#39;.&#39;+ scrollbarClass).css({width:width+&#39;px&#39;});}else if(scrollbarDistance&gt;=(scrollbarStageWidth- scrollMargin- scrollBorder- scrollbarWidth)){width=scrollbarStageWidth- scrollMargin- scrollBorder- scrollbarDistance;helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),scrollbarDistance);$(&#39;.&#39;+ scrollbarClass).css({width:width+&#39;px&#39;});}else{helpers.setSliderOffset($(&#39;.&#39;+ scrollbarClass),scrollbarDistance);}}
if(e.type==&#39;touchmove&#39;){lastTouch=e.touches[0].pageX;}
var slideChanged=false;var newChildOffset=helpers.calcActiveOffset(settings,(xScrollStartPosition- eventX- edgeDegradation)*-1,childrenOffsets,stageWidth,infiniteSliderOffset[sliderNumber],numberOfSlides,undefined,sliderNumber);var tempOffset=(newChildOffset+ infiniteSliderOffset[sliderNumber]+ numberOfSlides)%numberOfSlides;if(settings.infiniteSlider){if(tempOffset!=activeChildInfOffsets[sliderNumber]){slideChanged=true;}}else{if(newChildOffset!=activeChildOffsets[sliderNumber]){slideChanged=true;}}
if(slideChanged){activeChildOffsets[sliderNumber]=newChildOffset;activeChildInfOffsets[sliderNumber]=tempOffset;snapOverride=true;var args=new helpers.args(&#39;change&#39;,settings,scrollerNode,$(scrollerNode).children(&#39;:eq(&#39;+ tempOffset+&#39;)&#39;),tempOffset,tempOffset);$(stageNode).data(&#39;args&#39;,args);if(settings.onSlideChange!=&#39;&#39;){settings.onSlideChange(args);}}}});var eventObject=$(window);if(isIe8||isIe7){var eventObject=$(document);}
$(touchSelection).bind(&#39;touchend.iosSliderEvent&#39;,function(e){var e=e.originalEvent;if(touchLocks[sliderNumber]||shortContent)return true;if(isUnselectable)return true;if(e.touches.length!=0){for(var j=0;j&lt;e.touches.length;j++){if(e.touches[j].pageX==lastTouch){helpers.slowScrollHorizontal(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,xScrollDistance,yScrollDistance,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,currentEventNode,snapOverride,centeredSlideOffset,settings);}}}else{helpers.slowScrollHorizontal(scrollerNode,slideNodes,scrollTimeouts,scrollbarClass,xScrollDistance,yScrollDistance,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,currentEventNode,snapOverride,centeredSlideOffset,settings);}
preventXScroll=false;touchStartFlag=false;});$(eventObject).bind(&#39;mouseup.iosSliderEvent-&#39;+ sliderNumber,function(e){if(xScrollStarted){anchorEvents.unbind(&#39;click.disableClick&#39;).bind(&#39;click.disableClick&#39;,helpers.preventClick);}else{anchorEvents.unbind(&#39;click.disableClick&#39;).bind(&#39;click.disableClick&#39;,helpers.enableClick);}
onclickEvents.each(function(){this.onclick=function(event){if(xScrollStarted){return false;}
$(this).data(&#39;onclick&#39;).call(this,event||window.event);}
this.onclick=$(this).data(&#39;onclick&#39;);});if(parseFloat($().jquery)&gt;=1.8){allScrollerNodeChildren.each(function(){var clickObject=$._data(this,&#39;events&#39;);if(clickObject!=undefined){if(clickObject.click!=undefined){if(clickObject.click[0].namespace!=&#39;iosSliderEvent&#39;){if(!xScrollStarted){return false;}
$(this).one(&#39;click.disableClick&#39;,helpers.preventClick);var handlers=$._data(this,&#39;events&#39;).click;var handler=handlers.pop();handlers.splice(0,0,handler);}}}});}else if(parseFloat($().jquery)&gt;=1.6){allScrollerNodeChildren.each(function(){var clickObject=$(this).data(&#39;events&#39;);if(clickObject!=undefined){if(clickObject.click!=undefined){if(clickObject.click[0].namespace!=&#39;iosSliderEvent&#39;){if(!xScrollStarted){return false;}
$(this).one(&#39;click.disableClick&#39;,helpers.preventClick);var handlers=$(this).data(&#39;events&#39;).click;var handler=handlers.pop();handlers.splice(0,0,handler);}}}});}
if(!isEventCleared[sliderNumber]){if(shortContent)return true;if(touchLocks[sliderNumber])return true;$(touchSelection).css({cursor:grabOutCursor});isMouseDown=false;if(currentSlider==undefined){return true;}
helpers.slowScrollHorizontal(currentSlider,slideNodes,scrollTimeouts,scrollbarClass,xScrollDistance,yScrollDistance,scrollbarWidth,stageWidth,scrollbarStageWidth,scrollMargin,scrollBorder,originalOffsets,childrenOffsets,slideNodeOuterWidths,sliderNumber,infiniteSliderWidth,numberOfSlides,currentEventNode,snapOverride,centeredSlideOffset,settings);currentSlider=undefined;}
preventXScroll=false;touchStartFlag=false;});}});},destroy:function(clearStyle,node){if(node==undefined){node=this;}
return $(node).each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if(data==undefined)return false;if(clearStyle==undefined){clearStyle=true;}
helpers.autoSlidePause(data.sliderNumber);isEventCleared[data.sliderNumber]=true;$(window).unbind(&#39;.iosSliderEvent-&#39;+ data.sliderNumber);$(document).unbind(&#39;.iosSliderEvent-&#39;+ data.sliderNumber);$(document).unbind(&#39;keydown.iosSliderEvent&#39;);$(this).unbind(&#39;.iosSliderEvent&#39;);$(this).children(&#39;:first-child&#39;).unbind(&#39;.iosSliderEvent&#39;);$(this).children(&#39;:first-child&#39;).children().unbind(&#39;.iosSliderEvent&#39;);if(clearStyle){$(this).attr(&#39;style&#39;,&#39;&#39;);$(this).children(&#39;:first-child&#39;).attr(&#39;style&#39;,&#39;&#39;);$(this).children(&#39;:first-child&#39;).children().attr(&#39;style&#39;,&#39;&#39;);$(data.settings.navSlideSelector).attr(&#39;style&#39;,&#39;&#39;);$(data.settings.navPrevSelector).attr(&#39;style&#39;,&#39;&#39;);$(data.settings.navNextSelector).attr(&#39;style&#39;,&#39;&#39;);$(data.settings.autoSlideToggleSelector).attr(&#39;style&#39;,&#39;&#39;);$(data.settings.unselectableSelector).attr(&#39;style&#39;,&#39;&#39;);}
if(data.settings.scrollbar){$(&#39;.scrollbarBlock&#39;+ data.sliderNumber).remove();}
var scrollTimeouts=slideTimeouts[data.sliderNumber];for(var i=0;i&lt;scrollTimeouts.length;i++){clearTimeout(scrollTimeouts[i]);}
$this.removeData(&#39;iosslider&#39;);$this.removeData(&#39;args&#39;);});},update:function(node){if(node==undefined){node=this;}
return $(node).each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if(data==undefined)return false;data.settings.startAtSlide=$this.data(&#39;args&#39;).currentSlideNumber;methods.destroy(false,this);if((data.numberOfSlides!=1)&amp;&amp;data.settings.infiniteSlider){data.settings.startAtSlide=(activeChildOffsets[data.sliderNumber]+ 1+ infiniteSliderOffset[data.sliderNumber]+ data.numberOfSlides)%data.numberOfSlides;}
methods.init(data.settings,this);var args=new helpers.args(&#39;update&#39;,data.settings,data.scrollerNode,$(data.scrollerNode).children(&#39;:eq(&#39;+(data.settings.startAtSlide- 1)+&#39;)&#39;),data.settings.startAtSlide- 1,data.settings.startAtSlide- 1);$(data.stageNode).data(&#39;args&#39;,args);if(data.settings.onSliderUpdate!=&#39;&#39;){data.settings.onSliderUpdate(args);}});},addSlide:function(slideNode,slidePosition){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if(data==undefined)return false;if($(data.scrollerNode).children().length==0){$(data.scrollerNode).append(slideNode);$this.data(&#39;args&#39;).currentSlideNumber=1;}else if(!data.settings.infiniteSlider){if(slidePosition&lt;=data.numberOfSlides){$(data.scrollerNode).children(&#39;:eq(&#39;+(slidePosition- 1)+&#39;)&#39;).before(slideNode);}else{$(data.scrollerNode).children(&#39;:eq(&#39;+(slidePosition- 2)+&#39;)&#39;).after(slideNode);}
if($this.data(&#39;args&#39;).currentSlideNumber&gt;=slidePosition){$this.data(&#39;args&#39;).currentSlideNumber++;}}else{if(slidePosition==1){$(data.scrollerNode).children(&#39;:eq(0)&#39;).before(slideNode);}else{$(data.scrollerNode).children(&#39;:eq(&#39;+(slidePosition- 2)+&#39;)&#39;).after(slideNode);}
if((infiniteSliderOffset[data.sliderNumber]&lt;-1)&amp;&amp;(true)){activeChildOffsets[data.sliderNumber]--;}
if($this.data(&#39;args&#39;).currentSlideNumber&gt;=slidePosition){activeChildOffsets[data.sliderNumber]++;}}
$this.data(&#39;iosslider&#39;).numberOfSlides++;methods.update(this);});},removeSlide:function(slideNumber){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if(data==undefined)return false;$(data.scrollerNode).children(&#39;:eq(&#39;+(slideNumber- 1)+&#39;)&#39;).remove();if(activeChildOffsets[data.sliderNumber]&gt;(slideNumber- 1)){activeChildOffsets[data.sliderNumber]--;}
methods.update(this);});},goToSlide:function(slide,node){if(node==undefined){node=this;}
return $(node).each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;slide=(slide&gt;data.childrenOffsets.length)?data.childrenOffsets.length- 1:slide- 1;helpers.changeSlide(slide,$(data.scrollerNode),$(data.slideNodes),slideTimeouts[data.sliderNumber],data.scrollbarClass,data.scrollbarWidth,data.stageWidth,data.scrollbarStageWidth,data.scrollMargin,data.scrollBorder,data.originalOffsets,data.childrenOffsets,data.slideNodeOuterWidths,data.sliderNumber,data.infiniteSliderWidth,data.numberOfSlides,data.centeredSlideOffset,data.settings);});},prevSlide:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;var slide=(activeChildOffsets[data.sliderNumber]+ infiniteSliderOffset[data.sliderNumber]+ data.numberOfSlides)%data.numberOfSlides;if((slide&gt;0)||data.settings.infiniteSlider){helpers.changeSlide(slide- 1,$(data.scrollerNode),$(data.slideNodes),slideTimeouts[data.sliderNumber],data.scrollbarClass,data.scrollbarWidth,data.stageWidth,data.scrollbarStageWidth,data.scrollMargin,data.scrollBorder,data.originalOffsets,data.childrenOffsets,data.slideNodeOuterWidths,data.sliderNumber,data.infiniteSliderWidth,data.numberOfSlides,data.centeredSlideOffset,data.settings);}
activeChildOffsets[data.sliderNumber]=slide;});},nextSlide:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;var slide=(activeChildOffsets[data.sliderNumber]+ infiniteSliderOffset[data.sliderNumber]+ data.numberOfSlides)%data.numberOfSlides;if((slide&lt;data.childrenOffsets.length-1)||data.settings.infiniteSlider){helpers.changeSlide(slide+ 1,$(data.scrollerNode),$(data.slideNodes),slideTimeouts[data.sliderNumber],data.scrollbarClass,data.scrollbarWidth,data.stageWidth,data.scrollbarStageWidth,data.scrollMargin,data.scrollBorder,data.originalOffsets,data.childrenOffsets,data.slideNodeOuterWidths,data.sliderNumber,data.infiniteSliderWidth,data.numberOfSlides,data.centeredSlideOffset,data.settings);}
activeChildOffsets[data.sliderNumber]=slide;});},lock:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;$(data.scrollerNode).css({cursor:&#39;default&#39;});touchLocks[data.sliderNumber]=true;});},unlock:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;$(data.scrollerNode).css({cursor:grabOutCursor});touchLocks[data.sliderNumber]=false;});},getData:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;return data;});},autoSlidePause:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;iosSliderSettings[data.sliderNumber].autoSlide=false;helpers.autoSlidePause(data.sliderNumber);return data;});},autoSlidePlay:function(){return this.each(function(){var $this=$(this);var data=$this.data(&#39;iosslider&#39;);if((data==undefined)||data.shortContent)return false;iosSliderSettings[data.sliderNumber].autoSlide=true;helpers.autoSlide($(data.scrollerNode),$(data.slideNodes),slideTimeouts[data.sliderNumber],data.scrollbarClass,data.scrollbarWidth,data.stageWidth,data.scrollbarStageWidth,data.scrollMargin,data.scrollBorder,data.originalOffsets,data.childrenOffsets,data.slideNodeOuterWidths,data.sliderNumber,data.infiniteSliderWidth,data.numberOfSlides,data.centeredSlideOffset,data.settings);return data;});}}
$.fn.iosSlider=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else if(typeof method===&#39;object&#39;||!method){return methods.init.apply(this,arguments);}else{$.error(&#39;invalid method call!&#39;);}};})(jQuery);

																	
																	



